config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: 'customers/registrations' }
  resources :customers, only:[:show, :index]

  root to: 'homes#top'
  resources :posts, only:[:new, :create, :index, :show, :destroy] do
    resources :post_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(custoemr)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    @post.save
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :caption)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="text-dark">
  <div class="row  w-50 mx-auto mt-4">
    <h5 class="text-white mt-2">投稿一覧</h5>
    <%= link_to "新規投稿", new_post_path, class: 'btn btn-success new-button offset-9' %>
  </div>
  <% @posts.each do |post| %>
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= attachment_image_tag post.customer, :image, fallback:"no-image.png", class:"mt-3 rounded-circle ml-4", size: "80x50" %>
          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to post_path(post.id) do %>
                <strong><span><%= post.title %></span></strong>
              <% end %>
            </p>
            <p class="card-text">説明：<%= post.caption %></p>
            <span><i class="fas fa-user"></i>By <%= link_to post.customer.name, customer_path(post.customer), class:'text-dark' %> |</span>
            <span><%= link_to "#{post.post_comments.count}コメント", post_path(post.id),class:"text-dark" %> |</span>
            <span><%= l post.created_at, class:'text-dark' %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="content-title text-white p-4 mb-0">投稿フォーム</h5>
      <div class="form-body p-4">

        <%= form_with model: @post, local:true do |f| %>
        <div class="input-group mb-3 mt-4">
          <div class="input-group-prepend">
            <span class="input-group-text" aria-hidden="true"><i class="fas fa-paste"></i></span>
          </div>
          <%= f.text_field :title,class:"form-control", placeholder:"タイトル" %>
        </div>
        <%= f.text_area :caption,class:"form-control",rows:"3", placeholder:"説明" %>
        <hr>
        <%= f.submit '投稿', class:"btn btn-lg btn-block btn-success mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-detail py-5 text-dark">

  <div class="card w-75 mx-auto mt-4 shadow-lg">
    <div class ="col-2">
      <%= link_to "戻る", posts_path,class:'btn btn-secondary' %>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag @post.customer, :image, fallback: "no-image.png", size:'130x100', class:'my-auto' %>
        </div>
        <div class="col-10">
          <p class="card-title">
              <strong><span> <%= @post.title %></span></strong>
          </p>
          <p class="card-title">説明：<%= @post.caption %></p>
          <div class="row">
          <span><i class="fas fa-user"></i> By <%= @post.customer.name %> ｜ </span>
          <span><i class="fa fa-calendar"></i> <%= l @post.created_at %> ｜ </span>
          <span><i class="fa fa-comment"></i></span>
            <div id ="comment_count_area">
              <%= link_to "#{@post.post_comments.count}", post_path(@post.id), class:"text-dark" %>
            </div> ｜

            <% if @post.favorited_by?(current_customer) %>
              <span>
                <%= link_to(post_favorites_path(@post), method: :delete, class:"text-dark") do %>
                  <i class="fa fa-heart" aria-hidden="true"></i>
                <% end %>
                <%= @post.favorites.count %>
              </span>
              <% else %>
              <span>
                <%= link_to(post_favorites_path(@post), method: :post, class:"text-dark") do %>
                  <i class="far fa-heart" aria-hidden="true"></i>
                <% end %>
                <%= @post.favorites.count %>
              </span>
            <% end %>
          <% if @post.customer == current_customer %>
            <span> ｜ </span><%= link_to "削除",post_path(@post), class:"text-dark", method: :delete %>
          <% end %>
          </div>
        </div>
      </div>
      <hr>

       <div class="comments comments_area card-text">
        <h4 class="mt-3"><%= @post.post_comments.count %>件コメント</h4>
        <% @post.post_comments.each do |post_comment| %>
          <div class="media border mb-3">
            <%= attachment_image_tag post_comment.customer, :image, fallback: "no-image.png", size:'90x60', class:'my-auto' %>
            <div class="post-name my-auto">
              <%= post_comment.customer.name %>
            </div>
            <div class="media-body ml-4 p-3">
              <p><%= l post_comment.created_at %></p>
              <p><%= post_comment.comment %></p>
              <% if post_comment.customer == current_customer %>
                <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, class:"btn btn-danger pull-right", remote: true %>
              <% else %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <hr>

      <div class="new-comment comment_create card-text">
        <%= form_with(model:[@post, @post_comment], local: true) do |f| %>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">コメントする</label></br>
            <%= f.text_area :comment, rows:'5', placeholder:"コメントをここに",:size => "120*120" %>
          </div>
          <%= f.submit "送信する", class:"btn btn-lg btn-info mt-2 float-right" %>
        <% end %>
      </div>

    </div>
  </div>
</div>