config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: 'customers/registrations' }
  resources :customers, only:[:show, :index]

  root to: 'homes#top'
  resources :posts, only:[:new, :create, :index, :show, :destroy] do
    resources :post_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :image

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(custoemr)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # ログイン済ユーザーのみにアクセスを許可する
  before_action :authenticate_customer!

  # deviseコントローラーにストロングパラメータを追加する
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとimage_id,learning,hobby,a_wordのストロングパラメータ追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image_id, :learning, :hobby, :a_word])
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end


  private

  def customer_params
    params.require(:customer).permit(:name, :email, :image, :learning, :hobby, :a_word)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    favorite = post.customer.favorites.new(post_id: post.id)
    favorite.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = post.customer.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to post_path(post)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_customer.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    @post.save
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :caption)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer w-100 mx-auto pt-3 pb-1 shadow-sm bg-dark">
  <div class="container text-center">
    <p class="text-white small">Copyrights © moc moc All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class ="m-0 bg-dark">
  <nav class="navbar navbar-expand shadow-sm">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag('logo.png', size: "220x60") %></a>
      <ul class="navbar-nav ml-auto text-white">
        <% if customer_signed_in? %>
          <li class="nav-item text-white nav-link">
            <%= link_to "会員一覧", customers_path, class:'text-white' %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "投稿一覧", posts_path, class:'text-white' %>
          </li>
          <li class="nav-item text-white nav-link">
            <%= link_to "マイページ", customer_path(current_customer.id), class:'text-white' %>
          </li>
          <li class="nav-item text-white nav-link">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:'text-white' %>
          </li class="nav-item text-white nav-link">
        <% else %>
          <li class="nav-item text-white nav-link">
            <%= link_to "新規登録", new_customer_registration_path, class:'text-white' %>
          </li>
          <li class="nav-item text-white nav-link">
            <%= link_to "ログイン", new_customer_session_path, class:'text-white' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mocmoc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <section class="section"></section>
    <%= render 'layouts/footer' %>
  </body>
</html>